# Generated by Django 5.1.4 on 2025-10-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='customers',
        ),
    ]
